name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ACT:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      dir: "backend"
    defaults:
      run:
        working-directory: ${{ env.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "${{ env.dir }}/go.mod"
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Setup buildah
        run: apt-get update && apt-get -y install buildah
        if: ${{ env.ACT }}
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "backend"
          tags: "${{ github.sha }}"
          context: "${{ env.dir }}"
          containerfiles: "${{ env.dir }}/docker/Containerfile"
  build-component:
    runs-on: ubuntu-latest
    env:
      dir: component
    defaults:
      run:
        working-directory: "${{ env.dir }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK
        uses: actions/setup-java@v3
        with:
          cache: "gradle"
          java-version: 17
          distribution: "temurin"
          check-latest: true
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle build
        run: ./gradlew bootJar
      - uses: actions/upload-artifact@v3
        with:
          name: Component package
          path: "${{ env.dir }}/build/libs"
