name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      dir: "backend"
    defaults:
      run:
        working-directory: ${{ env.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Go installation
        uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-go"
          path: "/opt/hostedtoolcache/go"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "${{ env.dir }}/go.mod"
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Setup buildah
        run: apt-get update && apt-get -y install buildah
        if: ${{ env.ACT }}
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "backend"
          tags: "${{ github.sha }}"
          context: "${{ env.dir }}"
          containerfiles: "${{ env.dir }}/docker/Containerfile"
